---
title: "Study 2"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(skimr)
library(psych)
library(visdat)
library(sjPlot)

```

```{r s2ReadAndClean}

s2raw <- read_csv("../data/s2_spotify_join.csv") %>% 
  dplyr::filter(Finished == 1) %>% 
  naniar::replace_with_na_all(condition = ~.x == -99)
names(s2raw)

s2 <- s2raw %>% 
  mutate(id = rownames(.),
         age = age + 17,
         gender = fct_recode(as.factor(.$gender), 
                             "Male" = "0", 
                             "Female" = "1",
                             "Non-Binary/Not Disclosed" = "2"),
         Baseline = rowSums(dplyr::select(., deq_1_1:deq_1_4)),
         PostInduction = rowSums(dplyr::select(., deq_2_1: deq_2_4)),
         PostListening = rowSums(dplyr::select(., deq_3_1: deq_3_4)), 
         rrq_6 = 6 - rrq_6,
         rrq_9 = 6 - rrq_9,
         rrq_10 = 6 - rrq_10,
         musebaq = rowSums(dplyr::select(., musebaq_1:musebaq_9)))


s2 <- s2 %>% 
  mutate(rumination = rowMeans(dplyr::select(., rrq_1:rrq_12)))

s2 %>% 
  dplyr::select(Baseline,
                PostInduction,
                PostListening,
                rumination,
                musebaq,
                hours.listen,
                reg.use_1,
                age) %>% 
  skimr::skim() %>% 
  skimr::kable()

```

```{r alphas}

psych::alpha(dplyr::select(s2, deq_1_1:deq_1_4))$total$raw_alpha
psych::alpha(dplyr::select(s2, deq_2_1:deq_2_4))$total$raw_alpha
psych::alpha(dplyr::select(s2, deq_3_1:deq_3_4))$total$raw_alpha
psych::alpha(dplyr::select(s2, rrq_1:rrq_12))$total$raw_alpha
psych::alpha(dplyr::select(s2, musebaq_1:musebaq_9))$total$raw_alpha

```

# MNanipulation Check
```{r manipulationcheck}
S2Manipulation <- t.test(s2$PostInduction, s2$Baseline, paired = TRUE) 

apa::t_apa(S2Manipulation)

```

# Hypothesis Test
```{r PreRegTest}
s2long <- s2 %>% 
  gather(key = Timepoint,
         value = Sadness,
         PostInduction, PostListening)


S2glmm <- lme4::lmer(Sadness~1 + Timepoint + rumination + Timepoint*rumination + (1 |id), data = s2long)

tab_model(S2glmm)

sjPlot::plot_model(S2glmm,
                   type = "int",
                   mdrt.values = "meansd")

emmeans::emmip(S2glmm, rumination~Timepoint)


```

